---
title: "Working with Cell Selections"
author: "Nikolas Barkas"
date: "October 23, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Working with cell selections

Pagoda2 allows you to easily work with cell selections generated in R or via the web interface.

You can read a file of cell selections generated with the web interface using the readPagoda2SelectionFile() function. This will
generate a list object that contains all the information about the selections. 

You can make cell selection file from a web selection object generated in R using the writePagoda2SelectionFile() function. You can send
this file over email to unambigiously communicate cell subsets.

In R it is often easier to work with cell selections in the form of factors. To convert a selection to a factor you can use the 
factorFromP2Selection() function. This will returned a named factor of the membership of each cell in selections. However in order
to do this you will need to ensure that every cell belong only to one selection. You can check if any cells are in multiple clusters
and clean up your selection object using the functions: calcMulticlassified(), removeSelectionOverlaps(), plotSelectionOverlaps() and
plotMulticlassified(). 

You can also convert a factor to a pagoda2 selection using the factorToP2selection() function.

Other functions for working with selection in R include: getColorsFromP2Selection(), cellsPerSelectionGroup(), 
validateSelectionsObject(), getClusterLabelsFromSelection(), generateClassificationAnnotation(), getCellsInSelections(),
diffExprOnP2FromWebSelection(), diffExprOnP2FromWebSelectionOneGroup(), getIntExtNamesP2Selection() and plotEmbeddingColorByP2Selection()
