# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

WriteListToBinary <- function(expL, outfile, verbose = FALSE) {
    invisible(.Call('_pagoda2_WriteListToBinary', PACKAGE = 'pagoda2', expL, outfile, verbose))
}

checkBits <- function() {
    .Call('_pagoda2_checkBits', PACKAGE = 'pagoda2')
}

checkOpenMP <- function() {
    .Call('_pagoda2_checkOpenMP', PACKAGE = 'pagoda2')
}

referenceWij <- function(i, j, d, threads, perplexity) {
    .Call('_pagoda2_referenceWij', PACKAGE = 'pagoda2', i, j, d, threads, perplexity)
}

sgd <- function(coords, targets_i, sources_j, ps, weights, gamma, rho, n_samples, M, alpha, momentum, useDegree, seed, threads, verbose) {
    .Call('_pagoda2_sgd', PACKAGE = 'pagoda2', coords, targets_i, sources_j, ps, weights, gamma, rho, n_samples, M, alpha, momentum, useDegree, seed, threads, verbose)
}

non0LogColLmS <- function(sY, X, ldepth, maxCells = 0L, ncores = 1L) {
    .Call('_pagoda2_non0LogColLmS', PACKAGE = 'pagoda2', sY, X, ldepth, maxCells, ncores)
}

colMeanVarS <- function(sY, rowSel, ncores = 1L) {
    .Call('_pagoda2_colMeanVarS', PACKAGE = 'pagoda2', sY, rowSel, ncores)
}

colSumByFac <- function(sY, rowSel) {
    .Call('_pagoda2_colSumByFac', PACKAGE = 'pagoda2', sY, rowSel)
}

inplaceColMult <- function(sY, mult, rowSel, ncores = 1L) {
    .Call('_pagoda2_inplaceColMult', PACKAGE = 'pagoda2', sY, mult, rowSel, ncores)
}

inplaceWinsorizeSparseCols <- function(sY, n, ncores = 1L) {
    .Call('_pagoda2_inplaceWinsorizeSparseCols', PACKAGE = 'pagoda2', sY, n, ncores)
}

jsDist <- function(m, ncores = 1L) {
    .Call('_pagoda2_jsDist', PACKAGE = 'pagoda2', m, ncores)
}

orderColumnRows <- function(p, i) {
    .Call('_pagoda2_orderColumnRows', PACKAGE = 'pagoda2', p, i)
}

smatColVecCorr <- function(sY, sv, parallel = TRUE) {
    .Call('_pagoda2_smatColVecCorr', PACKAGE = 'pagoda2', sY, sv, parallel)
}

arma_mat_cor <- function(m) {
    .Call('_pagoda2_arma_mat_cor', PACKAGE = 'pagoda2', m)
}

matWCorr <- function(Mat, Matw) {
    .Call('_pagoda2_matWCorr', PACKAGE = 'pagoda2', Mat, Matw)
}

winsorizeMatrix <- function(Mat, Trim) {
    .Call('_pagoda2_winsorizeMatrix', PACKAGE = 'pagoda2', Mat, Trim)
}

plSemicompleteCor2 <- function(Pl) {
    .Call('_pagoda2_plSemicompleteCor2', PACKAGE = 'pagoda2', Pl)
}

avg_rank <- function(x) {
    .Call('_pagoda2_avg_rank', PACKAGE = 'pagoda2', x)
}

sparse_matrix_column_ranks <- function(sY) {
    .Call('_pagoda2_sparse_matrix_column_ranks', PACKAGE = 'pagoda2', sY)
}

nearbyPointsGreedyCluster <- function(p, windowSize) {
    .Call('_pagoda2_nearbyPointsGreedyCluster', PACKAGE = 'pagoda2', p, windowSize)
}

closestNPointsToSegments <- function(s, e, p, tss, N) {
    .Call('_pagoda2_closestNPointsToSegments', PACKAGE = 'pagoda2', s, e, p, tss, N)
}

closestNSegmentsToPoints <- function(s, e, p, tss, N) {
    .Call('_pagoda2_closestNSegmentsToPoints', PACKAGE = 'pagoda2', s, e, p, tss, N)
}

