# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

non0LogColLmS <- function(sY, X, ldepth, maxCells = 0L) {
    .Call('pagoda2_non0LogColLmS', PACKAGE = 'pagoda2', sY, X, ldepth, maxCells)
}

colMeanVarS <- function(sY, rowSel) {
    .Call('pagoda2_colMeanVarS', PACKAGE = 'pagoda2', sY, rowSel)
}

colSumByFac <- function(sY, rowSel) {
    .Call('pagoda2_colSumByFac', PACKAGE = 'pagoda2', sY, rowSel)
}

inplaceColMult <- function(sY, mult, rowSel) {
    .Call('pagoda2_inplaceColMult', PACKAGE = 'pagoda2', sY, mult, rowSel)
}

inplaceWinsorizeSparseCols <- function(sY, n) {
    .Call('pagoda2_inplaceWinsorizeSparseCols', PACKAGE = 'pagoda2', sY, n)
}

jsDist <- function(m) {
    .Call('pagoda2_jsDist', PACKAGE = 'pagoda2', m)
}

orderColumnRows <- function(p, i) {
    .Call('pagoda2_orderColumnRows', PACKAGE = 'pagoda2', p, i)
}

smatColVecCorr <- function(sY, sv, parallel = TRUE) {
    .Call('pagoda2_smatColVecCorr', PACKAGE = 'pagoda2', sY, sv, parallel)
}

hnswKnn <- function(m, efConstruction = 20L, indexThreadQty = 4L, searchMethod = 4L) {
    .Call('pagoda2_hnswKnn', PACKAGE = 'pagoda2', m, efConstruction, indexThreadQty, searchMethod)
}

hnswKnn2 <- function(m, k = 5L, nThreads = 30L, efConstruction = 20L, indexThreadQty = 4L, searchMethod = 4L, seed = -1L, verbose = TRUE) {
    .Call('pagoda2_hnswKnn2', PACKAGE = 'pagoda2', m, k, nThreads, efConstruction, indexThreadQty, searchMethod, seed, verbose)
}

hnswKnnJS <- function(m, k = 5L, nThreads = 20L, efConstruction = 20L, indexThreadQty = 4L, searchMethod = 4L, seed = -1L) {
    .Call('pagoda2_hnswKnnJS', PACKAGE = 'pagoda2', m, k, nThreads, efConstruction, indexThreadQty, searchMethod, seed)
}

hnswKnnLp <- function(m, k = 5L, nThreads = 30L, p = 2.0, efConstruction = 20L, indexThreadQty = 4L, searchMethod = 4L, seed = -1L, verbose = TRUE) {
    .Call('pagoda2_hnswKnnLp', PACKAGE = 'pagoda2', m, k, nThreads, p, efConstruction, indexThreadQty, searchMethod, seed, verbose)
}

hnswKnn3test <- function(m, k = 5L, multiplex = 1L, nqueries = 1000L, nThreads = 30L, efConstruction = 20L, indexThreadQty = 4L, searchMethod = 4L, seed = -1L, verbose = TRUE) {
    .Call('pagoda2_hnswKnn3test', PACKAGE = 'pagoda2', m, k, multiplex, nqueries, nThreads, efConstruction, indexThreadQty, searchMethod, seed, verbose)
}

winsorizeMatrix <- function(Mat, Trim) {
    .Call('pagoda2_winsorizeMatrix', PACKAGE = 'pagoda2', Mat, Trim)
}

avg_rank <- function(x) {
    .Call('pagoda2_avg_rank', PACKAGE = 'pagoda2', x)
}

sparse_matrix_column_ranks <- function(sY) {
    .Call('pagoda2_sparse_matrix_column_ranks', PACKAGE = 'pagoda2', sY)
}

nearbyPointsGreedyCluster <- function(p, windowSize) {
    .Call('pagoda2_nearbyPointsGreedyCluster', PACKAGE = 'pagoda2', p, windowSize)
}

closestNPointsToSegments <- function(s, e, p, tss, N) {
    .Call('pagoda2_closestNPointsToSegments', PACKAGE = 'pagoda2', s, e, p, tss, N)
}

closestNSegmentsToPoints <- function(s, e, p, tss, N) {
    .Call('pagoda2_closestNSegmentsToPoints', PACKAGE = 'pagoda2', s, e, p, tss, N)
}

