# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

WriteListToBinary <- function(expL, outfile) {
    invisible(.Call('_pagoda2_WriteListToBinary', PACKAGE = 'pagoda2', expL, outfile))
}

mutualNN <- function(mA, mB, kA, kB, spaceType = 2L) {
    .Call('_pagoda2_mutualNN', PACKAGE = 'pagoda2', mA, mB, kA, kB, spaceType)
}

non0LogColLmS <- function(sY, X, ldepth, maxCells = 0L) {
    .Call('_pagoda2_non0LogColLmS', PACKAGE = 'pagoda2', sY, X, ldepth, maxCells)
}

colMeanVarS <- function(sY, rowSel) {
    .Call('_pagoda2_colMeanVarS', PACKAGE = 'pagoda2', sY, rowSel)
}

colSumByFac <- function(sY, rowSel) {
    .Call('_pagoda2_colSumByFac', PACKAGE = 'pagoda2', sY, rowSel)
}

inplaceColMult <- function(sY, mult, rowSel) {
    .Call('_pagoda2_inplaceColMult', PACKAGE = 'pagoda2', sY, mult, rowSel)
}

inplaceWinsorizeSparseCols <- function(sY, n) {
    .Call('_pagoda2_inplaceWinsorizeSparseCols', PACKAGE = 'pagoda2', sY, n)
}

jsDist <- function(m) {
    .Call('_pagoda2_jsDist', PACKAGE = 'pagoda2', m)
}

orderColumnRows <- function(p, i) {
    .Call('_pagoda2_orderColumnRows', PACKAGE = 'pagoda2', p, i)
}

smatColVecCorr <- function(sY, sv, parallel = TRUE) {
    .Call('_pagoda2_smatColVecCorr', PACKAGE = 'pagoda2', sY, sv, parallel)
}

arma_mat_cor <- function(m) {
    .Call('_pagoda2_arma_mat_cor', PACKAGE = 'pagoda2', m)
}

hnswKnn2 <- function(m, k = 5L, nThreads = 20L, efConstruction = 20L, indexThreadQty = 4L, searchMethod = 4L, seed = -1L, verbose = TRUE) {
    .Call('_pagoda2_hnswKnn2', PACKAGE = 'pagoda2', m, k, nThreads, efConstruction, indexThreadQty, searchMethod, seed, verbose)
}

hnswKnnJS <- function(m, k = 5L, nThreads = 20L, efConstruction = 20L, indexThreadQty = 4L, searchMethod = 4L, seed = -1L, verbose = TRUE) {
    .Call('_pagoda2_hnswKnnJS', PACKAGE = 'pagoda2', m, k, nThreads, efConstruction, indexThreadQty, searchMethod, seed, verbose)
}

hnswKnnLp <- function(m, k = 5L, nThreads = 30L, p = 2.0, efConstruction = 20L, indexThreadQty = 4L, searchMethod = 4L, seed = -1L, verbose = TRUE) {
    .Call('_pagoda2_hnswKnnLp', PACKAGE = 'pagoda2', m, k, nThreads, p, efConstruction, indexThreadQty, searchMethod, seed, verbose)
}

matWCorr <- function(Mat, Matw) {
    .Call('_pagoda2_matWCorr', PACKAGE = 'pagoda2', Mat, Matw)
}

winsorizeMatrix <- function(Mat, Trim) {
    .Call('_pagoda2_winsorizeMatrix', PACKAGE = 'pagoda2', Mat, Trim)
}

plSemicompleteCor2 <- function(Pl) {
    .Call('_pagoda2_plSemicompleteCor2', PACKAGE = 'pagoda2', Pl)
}

avg_rank <- function(x) {
    .Call('_pagoda2_avg_rank', PACKAGE = 'pagoda2', x)
}

sparse_matrix_column_ranks <- function(sY) {
    .Call('_pagoda2_sparse_matrix_column_ranks', PACKAGE = 'pagoda2', sY)
}

nearbyPointsGreedyCluster <- function(p, windowSize) {
    .Call('_pagoda2_nearbyPointsGreedyCluster', PACKAGE = 'pagoda2', p, windowSize)
}

closestNPointsToSegments <- function(s, e, p, tss, N) {
    .Call('_pagoda2_closestNPointsToSegments', PACKAGE = 'pagoda2', s, e, p, tss, N)
}

closestNSegmentsToPoints <- function(s, e, p, tss, N) {
    .Call('_pagoda2_closestNSegmentsToPoints', PACKAGE = 'pagoda2', s, e, p, tss, N)
}

